# Service for ClusterIP
apiVersion: v1
kind: Service
metadata:
  name: api-students-service
spec:
  selector:
    app: api-students
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
