apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  labels:
    app: mysql-db
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql-db
    tier: database
  clusterIP: None # DNS is used, so clusterIP is not needed